version: '3'
services:
  minio:
    image: minio/minio
    volumes:
      - /Workspace/minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "access"
      MINIO_SECRET_KEY: "password"
    command: server /data