minio:
    endpoint: http://localhost:9000
    accessKey: access
    secretKey: password
    bucket: images
spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

